name: Rust

on: [push, pull_request]

jobs:
  test:
    name: cargo test
    uses: noir-lang/.github/.github/workflows/rust-test.yml@phated/name-jobs

  clippy:
    name: cargo clippy
    uses: noir-lang/.github/.github/workflows/rust-clippy.yml@phated/name-jobs

  format:
    name: cargo fmt
    uses: noir-lang/.github/.github/workflows/rust-format.yml@phated/name-jobs

  spellcheck:
    name: spellcheck
    uses: noir-lang/.github/.github/workflows/spellcheck.yml@phated/name-jobs
